### ISSUE TITLE
☂️ Luatest 22.Q3 [73sp]

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/luatest#215]
First-tier improvements in luatest

Moving luatest helpers from other repos to luatest

- [ ] https://github.com/tarantool/luatest/issues/237
- [ ] https://github.com/tarantool/luatest/issues/238
- [ ] https://github.com/tarantool/luatest/issues/239
- [ ] https://github.com/tarantool/test-run/issues/346

Logging and reporting

- [ ] https://github.com/tarantool/luatest/issues/201
- [ ] https://github.com/tarantool/test-run/issues/318
- [ ] https://github.com/tarantool/luatest/issues/225
- [x] https://github.com/tarantool/test-run/issues/319

Bugfixes and small improvements

- [x] https://github.com/tarantool/luatest/issues/152
- [x] https://github.com/tarantool/luatest/issues/171
- [x] https://github.com/tarantool/luatest/issues/172
- [x] https://github.com/tarantool/luatest/issues/155

**Comment by NickVolynkin** [comment]
Superseded by https://github.com/tarantool/luatest/issues/246
